### ISSUE TITLE
When using https scheme on /auth/v1.0/ returns 400 (Bad request)

### ISSUE THREAD

**Issue by Fuzi0n** [fanatic/swift-ui#4]
Hello Fanatic,

I've been playing around with your project. I encounter a wierd behavior:
* When using HTTP on auth url: it sends a GET (200) and everything works fine.
* When using HTTPS on auth_url: it sends a OPTIONS request then the API returns a bad request.

```<html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>```

Is there any reason why it behaves differently ? Do I have to enable a specific option in proxy-server.conf to handle the OPTIONS on auth_url ?

**Comment by fanatic** [comment]
Hello.  Sounds like you need to configure CORS on the Swift server side.  Try the sample CORS page [1] they provide and make sure it works as expected.  Although since you're having trouble with the auth_url, it could be specific to your auth provider [2].

[1] http://docs.openstack.org/developer/swift/cors.html
[2] http://docs.openstack.org/developer/swift/development_auth.html#allowing-cors-with-auth

**Comment by Fuzi0n** [comment]
Thx for your answers,

ATM we're using Tempauth, I took a look at the code: 
```
        if req.method == 'OPTIONS':
            #allow OPTIONS requests to proceed as normal
            self.logger.debug("Allow OPTIONS request.")
            return None
 ```
I will have a closer look later. Can you tell me why we should use HTTP options method in this case ?

**Comment by fanatic** [comment]
It's just how the browser is designed to be secure - a standard called CORS, nothing to do with the code itself.

**Comment by Fuzi0n** [comment]
Ok thanks for your explanation.
